spring:
  application:
      name: delivery-challenge
  profiles:
    active: dev
  liquibase:
    enabled: true
    change-log: classpath:/config/liquibase/master.xml
    dropFirst: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8083

resource-uri: https://api.github.com/user/repos

